use serde::{Deserialize, Serialize};
use std::path::Path;

use crate::dedup::DuplicatePair;
use crate::heuristics::PruneCandidate;

/// Comprehensive JSON audit report generated by the OVIS Pruning & Deduplication Engine.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PruneAuditReport {
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub total_documents_evaluated: usize,
    pub total_candidates_flagged: usize,
    pub total_duplicates_detected: usize,
    pub dry_run: bool,
    pub scope: String,
    pub candidates: Vec<PruneCandidate>,
    pub duplicate_pairs: Vec<DuplicatePair>,
}

impl PruneAuditReport {
    /// Serialize the audit report to a pretty-printed JSON string.
    pub fn to_json_pretty(&self) -> anyhow::Result<String> {
        let json_str = serde_json::to_string_pretty(self)?;
        Ok(json_str)
    }

    /// Save the audit report to a file on disk (creating parent directories if missing).
    pub fn save_to_file<P: AsRef<Path>>(&self, path: P) -> anyhow::Result<()> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                std::fs::create_dir_all(parent)?;
            }
        }
        let json_str = self.to_json_pretty()?;
        std::fs::write(path, json_str)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::heuristics::PruneFlagReason;

    #[test]
    fn test_prune_audit_report_serialization() {
        let report = PruneAuditReport {
            timestamp: chrono::Utc::now(),
            total_documents_evaluated: 10,
            total_candidates_flagged: 2,
            total_duplicates_detected: 1,
            dry_run: true,
            scope: "Engineering docs".to_string(),
            candidates: vec![PruneCandidate {
                document_id: "doc2".to_string(),
                title: "Stub Page".to_string(),
                connector_id: 1,
                flag_reasons: vec![PruneFlagReason {
                    rule_name: "min_char_count".to_string(),
                    description: "Too short".to_string(),
                    confidence: 1.0,
                }],
                duplicate_of: None,
            }],
            duplicate_pairs: vec![DuplicatePair {
                kept_document_id: "doc1".to_string(),
                duplicate_document_id: "doc2".to_string(),
                jaccard_similarity: 0.92,
                reason: "Keep longest content".to_string(),
            }],
        };

        let json_str = report
            .to_json_pretty()
            .expect("Failed to serialize audit report");
        assert!(json_str.contains("total_documents_evaluated"));
        assert!(json_str.contains("doc2"));

        let deserialized: PruneAuditReport =
            serde_json::from_str(&json_str).expect("Failed to deserialize audit report");
        assert_eq!(
            report.total_documents_evaluated,
            deserialized.total_documents_evaluated
        );
        assert_eq!(report.candidates.len(), deserialized.candidates.len());
    }
}
