-- Captured subset of the live Onyx schema (Onyx v4.3.4, Postgres 15.2 on gamma).
--
-- Generated by `scripts/capture-onyx-schema.sh`, which runs `pg_dump
-- --schema-only` over the 23 tables the OVIS data layer reads or sweeps, then
-- trims SET/ownership noise and orders the statements (sequences, tables, then
-- defaults, indexes and constraints) so the file restores standalone.
--
-- The integration tests run against this, so a query that passes them passes
-- against production for the same reason: it is the same DDL, with the same
-- types and — crucially — every foreign key the cascading delete has to clear.
--
-- Two deliberate trims:
--
--   * Foreign keys pointing *out* of this table set are dropped (6 of them,
--     e.g. `credential.user_id -> user`, `persona__document.persona_id -> persona`).
--     They would drag in Onyx's auth and chat graph, and OVIS reads none of it.
--     Every foreign key that references `document` is kept — those are exactly
--     what the delete sweep exists for.
--   * Trigger *functions* are captured separately (see below), because
--     `pg_dump -t <table>` carries triggers but not the functions they call.
--
-- Refresh after an Onyx upgrade:
--     scripts/capture-onyx-schema.sh gamma > tests/fixtures/onyx_schema.sql
--
-- Do not hand-edit; seed rows belong in `seed.sql`.

-- ---------------------------------------------------------------------------
-- Trigger functions, verbatim from `pg_get_functiondef`. Onyx's own
-- knowledge-graph bookkeeping: OVIS never calls them, but they do fire on
-- `semantic_id` updates, so the tests use the real ones rather than no-op stubs.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.update_kg_entity_name()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
            DECLARE
                name text;
                cleaned_name text;
            BEGIN
                -- Set name to semantic_id if document_id is not NULL
                IF NEW.document_id IS NOT NULL THEN
                    SELECT lower(semantic_id) INTO name
                    FROM "public".document
                    WHERE id = NEW.document_id;
                ELSE
                    name = lower(NEW.name);
                END IF;

                -- Clean name and truncate if too long
                cleaned_name = regexp_replace(
                    name,
                    '[^a-z0-9]+', '', 'g'
                );
                IF length(cleaned_name) > 1000 THEN
                    cleaned_name = left(cleaned_name, 1000);
                END IF;

                -- Set name and name trigrams
                NEW.name = name;
                NEW.name_trigrams = public.show_trgm(cleaned_name);
                RETURN NEW;
            END;
            $function$
;

CREATE OR REPLACE FUNCTION public.update_kg_entity_name_from_doc()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
            DECLARE
                doc_name text;
                cleaned_name text;
            BEGIN
                doc_name = lower(NEW.semantic_id);

                -- Clean name and truncate if too long
                cleaned_name = regexp_replace(
                    doc_name,
                    '[^a-z0-9]+', '', 'g'
                );
                IF length(cleaned_name) > 1000 THEN
                    cleaned_name = left(cleaned_name, 1000);
                END IF;

                -- Set name and name trigrams for all entities referencing this document
                UPDATE "public".kg_entity
                SET
                    name = doc_name,
                    name_trigrams = public.show_trgm(cleaned_name)
                WHERE document_id = NEW.id;
                RETURN NEW;
            END;
            $function$;

CREATE SEQUENCE public.api_key_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.background_error_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.chat_feedback_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.chat_message_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.code_interpreter_server_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.connector_credential_pair_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.connector_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.credential_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.discord_channel_config_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.discord_guild_config_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.doc_permission_sync_attempt_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.document_retrieval_feedback_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.document_set_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.embedding_model_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.external_app_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.external_app_policy_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.external_app_user_credential_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.external_group_permission_sync_attempt_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.federated_connector__document_set_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.federated_connector_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.federated_connector_oauth_token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.hierarchy_node_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.hook_execution_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.hook_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.index_attempt_errors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.index_attempt_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.index_attempt_stage_metric_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.inputprompt_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.internet_content_provider_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.internet_search_provider_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.license_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.llm_model_flow_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.llm_provider_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.mcp_connection_config_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.mcp_server_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.memory_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.model_configuration_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.notification_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.oauth_config_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.oauth_user_token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.opensearch_tenant_migration_record_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.permission_grant_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.persona_category_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.persona_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.personal_access_token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.saml_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.scheduled_task_pre_approved_app_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.scim_group_mapping_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.scim_token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.scim_user_mapping_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.search_doc_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.slack_bot_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.slack_channel_config_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.standard_answer_category_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.standard_answer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.sync_record_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.tag_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.targeted_reindex_job_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.task_queue_jobs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.tenant_usage_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.token_rate_limit_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.tool_call_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.tool_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.usage_reports_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.user_folder_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.user_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.voice_provider_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.background_error (
    id integer NOT NULL,
    message character varying NOT NULL,
    time_created timestamp with time zone DEFAULT now() NOT NULL,
    cc_pair_id integer
);

CREATE TABLE public.chunk_stats (
    id character varying NOT NULL,
    document_id character varying NOT NULL,
    chunk_in_doc_id integer NOT NULL,
    information_content_boost double precision,
    last_modified timestamp with time zone DEFAULT now() NOT NULL,
    last_synced timestamp with time zone
);

CREATE TABLE public.connector (
    id integer NOT NULL,
    name character varying NOT NULL,
    source character varying(50) NOT NULL,
    input_type character varying(10),
    connector_specific_config jsonb NOT NULL,
    refresh_freq integer,
    time_created timestamp with time zone DEFAULT now() NOT NULL,
    time_updated timestamp with time zone DEFAULT now() NOT NULL,
    prune_freq integer,
    indexing_start timestamp without time zone,
    kg_processing_enabled boolean DEFAULT false,
    kg_coverage_days integer
);

CREATE TABLE public.connector_credential_pair (
    connector_id integer NOT NULL,
    credential_id integer NOT NULL,
    last_successful_index_time timestamp with time zone,
    total_docs_indexed integer NOT NULL,
    id integer DEFAULT nextval('public.connector_credential_pair_id_seq'::regclass) NOT NULL,
    name character varying NOT NULL,
    status character varying(16) NOT NULL,
    deletion_failure_message character varying,
    access_type character varying NOT NULL,
    auto_sync_options jsonb,
    last_time_perm_sync timestamp with time zone,
    last_pruned timestamp with time zone,
    last_time_external_group_sync timestamp with time zone,
    creator_id uuid,
    indexing_trigger character varying(7),
    in_repeated_error_state boolean DEFAULT false,
    processing_mode character varying DEFAULT 'REGULAR'::character varying NOT NULL,
    last_time_hierarchy_fetch timestamp with time zone
);

CREATE TABLE public.credential (
    id integer NOT NULL,
    user_id uuid,
    time_created timestamp with time zone DEFAULT now() NOT NULL,
    time_updated timestamp with time zone DEFAULT now() NOT NULL,
    admin_public boolean NOT NULL,
    credential_json bytea,
    source character varying(100),
    name character varying,
    curator_public boolean DEFAULT false NOT NULL
);

CREATE TABLE public.document (
    id character varying NOT NULL,
    boost integer NOT NULL,
    hidden boolean NOT NULL,
    semantic_id character varying NOT NULL,
    link character varying,
    doc_updated_at timestamp with time zone,
    primary_owners character varying[],
    secondary_owners character varying[],
    from_ingestion_api boolean,
    last_modified timestamp with time zone DEFAULT now() NOT NULL,
    last_synced timestamp with time zone,
    external_user_emails character varying[],
    external_user_group_ids character varying[],
    is_public boolean,
    chunk_count integer,
    kg_stage character varying,
    kg_processing_time timestamp with time zone,
    doc_metadata jsonb,
    parent_hierarchy_node_id integer,
    file_id character varying,
    content_hash character varying
);

CREATE TABLE public.document__tag (
    document_id character varying NOT NULL,
    tag_id integer NOT NULL
);

CREATE TABLE public.document_by_connector_credential_pair (
    id character varying NOT NULL,
    connector_id integer NOT NULL,
    credential_id integer NOT NULL,
    has_been_indexed boolean NOT NULL
);

CREATE TABLE public.document_retrieval_feedback (
    id integer NOT NULL,
    document_id character varying NOT NULL,
    document_rank integer NOT NULL,
    clicked boolean NOT NULL,
    feedback character varying,
    chat_message_id integer
);

CREATE TABLE public.search_settings (
    id integer NOT NULL,
    model_name character varying NOT NULL,
    model_dim integer NOT NULL,
    "normalize" boolean NOT NULL,
    query_prefix character varying NOT NULL,
    passage_prefix character varying NOT NULL,
    index_name character varying NOT NULL,
    status character varying,
    provider_type character varying(50),
    multipass_indexing boolean DEFAULT false NOT NULL,
    embedding_precision character varying(8) DEFAULT 'FLOAT'::character varying NOT NULL,
    reduced_dimension integer,
    enable_contextual_rag boolean DEFAULT false NOT NULL,
    switchover_type character varying(11) DEFAULT 'reindex'::character varying NOT NULL,
    contextual_rag_model_configuration_id integer
);

CREATE TABLE public.hierarchy_node (
    id integer NOT NULL,
    raw_node_id character varying NOT NULL,
    display_name character varying NOT NULL,
    link character varying,
    source character varying NOT NULL,
    node_type character varying NOT NULL,
    document_id character varying,
    parent_id integer,
    external_user_emails character varying[],
    external_user_group_ids character varying[],
    is_public boolean DEFAULT false NOT NULL
);

CREATE TABLE public.index_attempt (
    id integer NOT NULL,
    time_created timestamp with time zone DEFAULT now() NOT NULL,
    time_updated timestamp with time zone DEFAULT now() NOT NULL,
    status character varying NOT NULL,
    error_msg character varying,
    total_docs_indexed integer,
    time_started timestamp with time zone,
    new_docs_indexed integer,
    from_beginning boolean NOT NULL,
    full_exception_trace text,
    docs_removed_from_index integer,
    connector_credential_pair_id integer NOT NULL,
    search_settings_id integer,
    checkpoint_pointer character varying,
    poll_range_start timestamp with time zone,
    poll_range_end timestamp with time zone,
    celery_task_id character varying,
    cancellation_requested boolean DEFAULT false NOT NULL,
    total_batches integer,
    completed_batches integer DEFAULT 0 NOT NULL,
    total_failures_batch_level integer DEFAULT 0 NOT NULL,
    total_chunks integer DEFAULT 0 NOT NULL,
    last_progress_time timestamp with time zone,
    last_batches_completed_count integer DEFAULT 0 NOT NULL,
    heartbeat_counter integer DEFAULT 0 NOT NULL,
    last_heartbeat_value integer DEFAULT 0 NOT NULL,
    last_heartbeat_time timestamp with time zone,
    targeted_reindex_job_id integer
);

CREATE TABLE public.index_attempt_errors (
    id integer NOT NULL,
    index_attempt_id integer NOT NULL,
    connector_credential_pair_id integer NOT NULL,
    document_id character varying,
    document_link character varying,
    entity_id character varying,
    failed_time_range_start timestamp with time zone,
    failed_time_range_end timestamp with time zone,
    failure_message text NOT NULL,
    is_resolved boolean NOT NULL,
    time_created timestamp with time zone DEFAULT now() NOT NULL,
    error_type character varying
);

CREATE TABLE public.kg_entity (
    id_name character varying NOT NULL,
    name character varying NOT NULL,
    entity_key character varying,
    name_trigrams character varying(3)[],
    document_id character varying,
    alternative_names character varying[] DEFAULT '{}'::character varying[] NOT NULL,
    entity_type_id_name character varying NOT NULL,
    description character varying,
    keywords character varying[] DEFAULT '{}'::character varying[] NOT NULL,
    occurrences integer DEFAULT 1 NOT NULL,
    acl character varying[] DEFAULT '{}'::character varying[] NOT NULL,
    boosts jsonb DEFAULT '{}'::jsonb NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_time timestamp with time zone,
    time_updated timestamp with time zone DEFAULT now(),
    time_created timestamp with time zone DEFAULT now(),
    parent_key character varying
);

CREATE TABLE public.kg_entity_extraction_staging (
    id_name character varying NOT NULL,
    name character varying NOT NULL,
    document_id character varying,
    alternative_names character varying[] DEFAULT '{}'::character varying[] NOT NULL,
    entity_type_id_name character varying NOT NULL,
    description character varying,
    keywords character varying[] DEFAULT '{}'::character varying[] NOT NULL,
    occurrences integer DEFAULT 1 NOT NULL,
    acl character varying[] DEFAULT '{}'::character varying[] NOT NULL,
    boosts jsonb DEFAULT '{}'::jsonb NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    transferred_id_name character varying,
    entity_key character varying,
    parent_key character varying,
    event_time timestamp with time zone,
    time_created timestamp with time zone DEFAULT now()
);

CREATE TABLE public.kg_entity_type (
    id_name character varying NOT NULL,
    description character varying,
    grounding character varying NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    occurrences integer DEFAULT 1 NOT NULL,
    active boolean NOT NULL,
    deep_extraction boolean NOT NULL,
    time_updated timestamp with time zone DEFAULT now(),
    time_created timestamp with time zone DEFAULT now(),
    grounded_source_name character varying,
    entity_values character varying[],
    clustering jsonb DEFAULT '{}'::jsonb NOT NULL
);

CREATE TABLE public.kg_relationship (
    id_name character varying NOT NULL,
    source_node character varying NOT NULL,
    target_node character varying NOT NULL,
    source_node_type character varying NOT NULL,
    target_node_type character varying NOT NULL,
    source_document character varying NOT NULL,
    type character varying NOT NULL,
    relationship_type_id_name character varying NOT NULL,
    occurrences integer DEFAULT 1 NOT NULL,
    time_updated timestamp with time zone DEFAULT now(),
    time_created timestamp with time zone DEFAULT now()
);

CREATE TABLE public.kg_relationship_extraction_staging (
    id_name character varying NOT NULL,
    source_node character varying NOT NULL,
    target_node character varying NOT NULL,
    source_node_type character varying NOT NULL,
    target_node_type character varying NOT NULL,
    source_document character varying NOT NULL,
    type character varying NOT NULL,
    relationship_type_id_name character varying NOT NULL,
    occurrences integer DEFAULT 1 NOT NULL,
    transferred boolean DEFAULT false NOT NULL,
    time_created timestamp with time zone DEFAULT now()
);

CREATE TABLE public.kg_relationship_type (
    id_name character varying NOT NULL,
    name character varying NOT NULL,
    source_entity_type_id_name character varying NOT NULL,
    target_entity_type_id_name character varying NOT NULL,
    definition boolean NOT NULL,
    occurrences integer DEFAULT 1 NOT NULL,
    type character varying NOT NULL,
    active boolean NOT NULL,
    time_updated timestamp with time zone DEFAULT now(),
    time_created timestamp with time zone DEFAULT now(),
    clustering jsonb DEFAULT '{}'::jsonb NOT NULL
);

CREATE TABLE public.kg_relationship_type_extraction_staging (
    id_name character varying NOT NULL,
    name character varying NOT NULL,
    source_entity_type_id_name character varying NOT NULL,
    target_entity_type_id_name character varying NOT NULL,
    definition boolean NOT NULL,
    occurrences integer DEFAULT 1 NOT NULL,
    type character varying NOT NULL,
    active boolean NOT NULL,
    time_created timestamp with time zone DEFAULT now(),
    clustering jsonb DEFAULT '{}'::jsonb NOT NULL,
    transferred boolean DEFAULT false NOT NULL
);

CREATE TABLE public.opensearch_document_migration_record (
    document_id character varying NOT NULL,
    status character varying DEFAULT 'pending'::character varying NOT NULL,
    error_message text,
    attempts_count integer DEFAULT 0 NOT NULL,
    last_attempt_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.persona__document (
    persona_id integer NOT NULL,
    document_id character varying NOT NULL
);

CREATE TABLE public.tag (
    id integer NOT NULL,
    tag_key character varying NOT NULL,
    tag_value character varying NOT NULL,
    source character varying(50) NOT NULL,
    is_list boolean DEFAULT false NOT NULL
);

ALTER SEQUENCE public.background_error_id_seq OWNED BY public.background_error.id;

ALTER SEQUENCE public.connector_id_seq OWNED BY public.connector.id;

ALTER SEQUENCE public.credential_id_seq OWNED BY public.credential.id;

ALTER SEQUENCE public.document_retrieval_feedback_id_seq OWNED BY public.document_retrieval_feedback.id;

ALTER SEQUENCE public.embedding_model_id_seq OWNED BY public.search_settings.id;

ALTER SEQUENCE public.hierarchy_node_id_seq OWNED BY public.hierarchy_node.id;

ALTER SEQUENCE public.index_attempt_errors_id_seq OWNED BY public.index_attempt_errors.id;

ALTER SEQUENCE public.index_attempt_id_seq OWNED BY public.index_attempt.id;

ALTER SEQUENCE public.tag_id_seq OWNED BY public.tag.id;

ALTER TABLE ONLY public.background_error ALTER COLUMN id SET DEFAULT nextval('public.background_error_id_seq'::regclass);

ALTER TABLE ONLY public.connector ALTER COLUMN id SET DEFAULT nextval('public.connector_id_seq'::regclass);

ALTER TABLE ONLY public.credential ALTER COLUMN id SET DEFAULT nextval('public.credential_id_seq'::regclass);

ALTER TABLE ONLY public.document_retrieval_feedback ALTER COLUMN id SET DEFAULT nextval('public.document_retrieval_feedback_id_seq'::regclass);

ALTER TABLE ONLY public.hierarchy_node ALTER COLUMN id SET DEFAULT nextval('public.hierarchy_node_id_seq'::regclass);

ALTER TABLE ONLY public.index_attempt ALTER COLUMN id SET DEFAULT nextval('public.index_attempt_id_seq'::regclass);

ALTER TABLE ONLY public.index_attempt_errors ALTER COLUMN id SET DEFAULT nextval('public.index_attempt_errors_id_seq'::regclass);

ALTER TABLE ONLY public.search_settings ALTER COLUMN id SET DEFAULT nextval('public.embedding_model_id_seq'::regclass);

ALTER TABLE ONLY public.tag ALTER COLUMN id SET DEFAULT nextval('public.tag_id_seq'::regclass);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT _tag_key_value_source_list_uc UNIQUE (tag_key, tag_value, source, is_list);

ALTER TABLE ONLY public.background_error
    ADD CONSTRAINT background_error_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chunk_stats
    ADD CONSTRAINT chunk_stats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.connector_credential_pair
    ADD CONSTRAINT connector_credential_pair__id__key UNIQUE (id);

ALTER TABLE ONLY public.connector_credential_pair
    ADD CONSTRAINT connector_credential_pair_pkey PRIMARY KEY (connector_id, credential_id);

ALTER TABLE ONLY public.connector
    ADD CONSTRAINT connector_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.credential
    ADD CONSTRAINT credential_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.document__tag
    ADD CONSTRAINT document__tag_pkey PRIMARY KEY (document_id, tag_id);

ALTER TABLE ONLY public.document_by_connector_credential_pair
    ADD CONSTRAINT document_by_connector_credential_pair_pkey PRIMARY KEY (id, connector_id, credential_id);

ALTER TABLE ONLY public.document
    ADD CONSTRAINT document_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.document_retrieval_feedback
    ADD CONSTRAINT document_retrieval_feedback_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.search_settings
    ADD CONSTRAINT embedding_model_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.hierarchy_node
    ADD CONSTRAINT hierarchy_node_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.index_attempt_errors
    ADD CONSTRAINT index_attempt_errors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.index_attempt
    ADD CONSTRAINT index_attempt_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.kg_entity_extraction_staging
    ADD CONSTRAINT kg_entity_extraction_staging_pkey PRIMARY KEY (id_name);

ALTER TABLE ONLY public.kg_entity
    ADD CONSTRAINT kg_entity_pkey PRIMARY KEY (id_name);

ALTER TABLE ONLY public.kg_entity_type
    ADD CONSTRAINT kg_entity_type_pkey PRIMARY KEY (id_name);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT kg_relationship_extraction_staging_pkey PRIMARY KEY (id_name, source_document);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT kg_relationship_pkey PRIMARY KEY (id_name, source_document);

ALTER TABLE ONLY public.kg_relationship_type_extraction_staging
    ADD CONSTRAINT kg_relationship_type_extraction_staging_pkey PRIMARY KEY (id_name);

ALTER TABLE ONLY public.kg_relationship_type
    ADD CONSTRAINT kg_relationship_type_pkey PRIMARY KEY (id_name);

ALTER TABLE ONLY public.opensearch_document_migration_record
    ADD CONSTRAINT opensearch_document_migration_record_pkey PRIMARY KEY (document_id);

ALTER TABLE ONLY public.persona__document
    ADD CONSTRAINT persona__document_pkey PRIMARY KEY (persona_id, document_id);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chunk_stats
    ADD CONSTRAINT uq_chunk_stats_doc_chunk UNIQUE (document_id, chunk_in_doc_id);

ALTER TABLE ONLY public.hierarchy_node
    ADD CONSTRAINT uq_hierarchy_node_raw_id_source UNIQUE (raw_node_id, source);

ALTER TABLE ONLY public.kg_entity
    ADD CONSTRAINT uq_kg_entity_name_type_doc UNIQUE (name, entity_type_id_name, document_id);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT uq_kg_relationship_extraction_staging_source_target_type UNIQUE (source_node, target_node, type);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT uq_kg_relationship_source_target_type UNIQUE (source_node, target_node, type);

CREATE INDEX idx_document_cc_pair_connector_credential ON public.document_by_connector_credential_pair USING btree (connector_id, credential_id);

CREATE INDEX idx_document_cc_pair_counts ON public.document_by_connector_credential_pair USING btree (connector_id, credential_id, has_been_indexed);

CREATE INDEX ix_chunk_stats_document_id ON public.chunk_stats USING btree (document_id);

CREATE INDEX ix_chunk_stats_last_modified ON public.chunk_stats USING btree (last_modified);

CREATE INDEX ix_chunk_stats_last_synced ON public.chunk_stats USING btree (last_synced);

CREATE INDEX ix_chunk_sync_status ON public.chunk_stats USING btree (last_modified, last_synced);

CREATE INDEX ix_document__tag_tag_id ON public.document__tag USING btree (tag_id);

CREATE INDEX ix_document_by_connector_credential_pair_pkey__connecto_27dc ON public.document_by_connector_credential_pair USING btree (connector_id, credential_id);

CREATE INDEX ix_document_kg_stage ON public.document USING btree (kg_stage);

CREATE INDEX ix_document_last_modified ON public.document USING btree (last_modified);

CREATE INDEX ix_document_last_synced ON public.document USING btree (last_synced);

CREATE INDEX ix_document_needs_sync ON public.document USING btree (id) WHERE ((last_modified > last_synced) OR (last_synced IS NULL));

CREATE INDEX ix_document_parent_hierarchy_node_id ON public.document USING btree (parent_hierarchy_node_id);

CREATE INDEX ix_hierarchy_node_document_id ON public.hierarchy_node USING btree (document_id);

CREATE INDEX ix_hierarchy_node_parent_id ON public.hierarchy_node USING btree (parent_id);

CREATE INDEX ix_hierarchy_node_source_type ON public.hierarchy_node USING btree (source, node_type);

CREATE INDEX ix_index_attempt_active_coordination ON public.index_attempt USING btree (connector_credential_pair_id, search_settings_id, status);

CREATE INDEX ix_index_attempt_cc_pair_settings_poll ON public.index_attempt USING btree (connector_credential_pair_id, search_settings_id, status, time_updated DESC);

CREATE INDEX ix_index_attempt_ccpair_search_settings_time_updated ON public.index_attempt USING btree (connector_credential_pair_id, search_settings_id, time_updated DESC);

CREATE INDEX ix_index_attempt_connector_credential_pair_id ON public.index_attempt USING btree (connector_credential_pair_id);

CREATE INDEX ix_index_attempt_errors_connector_credential_pair_id ON public.index_attempt_errors USING btree (connector_credential_pair_id);

CREATE INDEX ix_index_attempt_errors_index_attempt_id ON public.index_attempt_errors USING btree (index_attempt_id);

CREATE INDEX ix_index_attempt_latest_for_connector_credential_pair ON public.index_attempt USING btree (connector_credential_pair_id, time_created);

CREATE INDEX ix_index_attempt_status ON public.index_attempt USING btree (status);

CREATE INDEX ix_index_attempt_targeted_reindex_job_id ON public.index_attempt USING btree (targeted_reindex_job_id);

CREATE INDEX ix_index_attempt_time_created ON public.index_attempt USING btree (time_created);

CREATE INDEX ix_opensearch_document_migration_record_attempts_count ON public.opensearch_document_migration_record USING btree (attempts_count);

CREATE INDEX ix_opensearch_document_migration_record_created_at ON public.opensearch_document_migration_record USING btree (created_at);

CREATE INDEX ix_opensearch_document_migration_record_status ON public.opensearch_document_migration_record USING btree (status);

CREATE INDEX ix_ovis_dcc_by_doc ON public.document_by_connector_credential_pair USING btree (id);

CREATE INDEX ix_ovis_document_boost ON public.document USING btree (boost DESC, id DESC);

CREATE INDEX ix_ovis_document_chunk_count ON public.document USING btree (chunk_count, id DESC);

CREATE INDEX ix_ovis_document_chunk_count_desc ON public.document USING btree (chunk_count DESC NULLS LAST, id DESC);

CREATE INDEX ix_ovis_document_id_trgm ON public.document USING gin (id public.gin_trgm_ops);

CREATE INDEX ix_ovis_document_semantic_id_trgm ON public.document USING gin (semantic_id public.gin_trgm_ops);

CREATE INDEX ix_ovis_document_tag_by_tag ON public.document__tag USING btree (tag_id);

CREATE INDEX ix_ovis_document_updated ON public.document USING btree (COALESCE(doc_updated_at, last_modified) DESC, id DESC);

CREATE INDEX ix_persona__document_document_id ON public.persona__document USING btree (document_id);

CREATE UNIQUE INDEX uq_hierarchy_node_one_source_per_type ON public.hierarchy_node USING btree (source) WHERE ((node_type)::text = 'SOURCE'::text);

CREATE TRIGGER update_kg_entity_name_from_doc_trigger AFTER UPDATE OF semantic_id ON public.document FOR EACH ROW EXECUTE FUNCTION public.update_kg_entity_name_from_doc();

CREATE TRIGGER update_kg_entity_name_trigger BEFORE INSERT OR UPDATE OF name ON public.kg_entity FOR EACH ROW EXECUTE FUNCTION public.update_kg_entity_name();

ALTER TABLE ONLY public.background_error
    ADD CONSTRAINT background_error_cc_pair_id_fkey FOREIGN KEY (cc_pair_id) REFERENCES public.connector_credential_pair(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.chunk_stats
    ADD CONSTRAINT chunk_stats_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id);

ALTER TABLE ONLY public.connector_credential_pair
    ADD CONSTRAINT connector_credential_pair_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.connector(id);

ALTER TABLE ONLY public.connector_credential_pair
    ADD CONSTRAINT connector_credential_pair_credential_id_fkey FOREIGN KEY (credential_id) REFERENCES public.credential(id);

ALTER TABLE ONLY public.document__tag
    ADD CONSTRAINT document__tag_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id);

ALTER TABLE ONLY public.document__tag
    ADD CONSTRAINT document__tag_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tag(id);

ALTER TABLE ONLY public.document_by_connector_credential_pair
    ADD CONSTRAINT document_by_connector_credential_pair_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES public.connector(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.document_by_connector_credential_pair
    ADD CONSTRAINT document_by_connector_credential_pair_credential_id_fkey FOREIGN KEY (credential_id) REFERENCES public.credential(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.document_by_connector_credential_pair
    ADD CONSTRAINT document_by_connector_credential_pair_id_fkey FOREIGN KEY (id) REFERENCES public.document(id);

ALTER TABLE ONLY public.document_retrieval_feedback
    ADD CONSTRAINT document_retrieval_feedback_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id);

ALTER TABLE ONLY public.document
    ADD CONSTRAINT fk_document_parent_hierarchy_node FOREIGN KEY (parent_hierarchy_node_id) REFERENCES public.hierarchy_node(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.index_attempt
    ADD CONSTRAINT fk_index_attempt_connector_credential_pair_id FOREIGN KEY (connector_credential_pair_id) REFERENCES public.connector_credential_pair(id);

ALTER TABLE ONLY public.index_attempt
    ADD CONSTRAINT fk_index_attempt_search_settings FOREIGN KEY (search_settings_id) REFERENCES public.search_settings(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.hierarchy_node
    ADD CONSTRAINT hierarchy_node_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.hierarchy_node
    ADD CONSTRAINT hierarchy_node_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.hierarchy_node(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.index_attempt_errors
    ADD CONSTRAINT index_attempt_errors_connector_credential_pair_id_fkey FOREIGN KEY (connector_credential_pair_id) REFERENCES public.connector_credential_pair(id);

ALTER TABLE ONLY public.index_attempt_errors
    ADD CONSTRAINT index_attempt_errors_index_attempt_id_fkey FOREIGN KEY (index_attempt_id) REFERENCES public.index_attempt(id);

ALTER TABLE ONLY public.kg_entity
    ADD CONSTRAINT kg_entity_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id);

ALTER TABLE ONLY public.kg_entity
    ADD CONSTRAINT kg_entity_entity_type_id_name_fkey FOREIGN KEY (entity_type_id_name) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_entity_extraction_staging
    ADD CONSTRAINT kg_entity_extraction_staging_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id);

ALTER TABLE ONLY public.kg_entity_extraction_staging
    ADD CONSTRAINT kg_entity_extraction_staging_entity_type_id_name_fkey FOREIGN KEY (entity_type_id_name) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT kg_relationship_extraction_stagi_relationship_type_id_name_fkey FOREIGN KEY (relationship_type_id_name) REFERENCES public.kg_relationship_type_extraction_staging(id_name);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT kg_relationship_extraction_staging_source_document_fkey FOREIGN KEY (source_document) REFERENCES public.document(id);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT kg_relationship_extraction_staging_source_node_fkey FOREIGN KEY (source_node) REFERENCES public.kg_entity_extraction_staging(id_name);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT kg_relationship_extraction_staging_source_node_type_fkey FOREIGN KEY (source_node_type) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT kg_relationship_extraction_staging_target_node_fkey FOREIGN KEY (target_node) REFERENCES public.kg_entity_extraction_staging(id_name);

ALTER TABLE ONLY public.kg_relationship_extraction_staging
    ADD CONSTRAINT kg_relationship_extraction_staging_target_node_type_fkey FOREIGN KEY (target_node_type) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT kg_relationship_relationship_type_id_name_fkey FOREIGN KEY (relationship_type_id_name) REFERENCES public.kg_relationship_type(id_name);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT kg_relationship_source_document_fkey FOREIGN KEY (source_document) REFERENCES public.document(id);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT kg_relationship_source_node_fkey FOREIGN KEY (source_node) REFERENCES public.kg_entity(id_name);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT kg_relationship_source_node_type_fkey FOREIGN KEY (source_node_type) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT kg_relationship_target_node_fkey FOREIGN KEY (target_node) REFERENCES public.kg_entity(id_name);

ALTER TABLE ONLY public.kg_relationship
    ADD CONSTRAINT kg_relationship_target_node_type_fkey FOREIGN KEY (target_node_type) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship_type_extraction_staging
    ADD CONSTRAINT kg_relationship_type_extraction_source_entity_type_id_name_fkey FOREIGN KEY (source_entity_type_id_name) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship_type_extraction_staging
    ADD CONSTRAINT kg_relationship_type_extraction_target_entity_type_id_name_fkey FOREIGN KEY (target_entity_type_id_name) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship_type
    ADD CONSTRAINT kg_relationship_type_source_entity_type_id_name_fkey FOREIGN KEY (source_entity_type_id_name) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.kg_relationship_type
    ADD CONSTRAINT kg_relationship_type_target_entity_type_id_name_fkey FOREIGN KEY (target_entity_type_id_name) REFERENCES public.kg_entity_type(id_name);

ALTER TABLE ONLY public.opensearch_document_migration_record
    ADD CONSTRAINT opensearch_document_migration_record_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.persona__document
    ADD CONSTRAINT persona__document_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document(id) ON DELETE CASCADE;
